import { notFound } from "next/navigation";
import { Instagram, ShieldCheck, Users } from "lucide-react";
import { CTAButton } from "@/components/CTAButton";
import { MemberCard } from "@/components/MemberCard";
import { SectionHeader } from "@/components/SectionHeader";
import { demoMembers, memberPageText } from "@/lib/members";
import { isLocale, links, type Locale } from "@/lib/i18n";

const cardPageCopy = {
  fr: {
    title: "Carte virtuelle de démonstration",
    text:
      "Votre carte réelle est générée par l’équipe Golden Circle après création de votre compte membre.",
    account: "Mon espace",
    instagram: "Suivre Instagram",
    gcList: "Rejoindre la GC List"
  },
  en: {
    title: "Demo virtual card",
    text:
      "Your real card is generated by the Golden Circle team after your member account is created.",
    account: "My space",
    instagram: "Follow Instagram",
    gcList: "Join the GC List"
  },
  es: {
    title: "Tarjeta virtual demo",
    text:
      "Tu tarjeta real es generada por el equipo Golden Circle después de crear tu cuenta miembro.",
    account: "Mi espacio",
    instagram: "Seguir Instagram",
    gcList: "Unirse a la GC List"
  },
  pt: {
    title: "Cartão virtual demo",
    text:
      "Seu cartão real é gerado pela equipe Golden Circle depois da criação da sua conta de membro.",
    account: "Meu espaço",
    instagram: "Seguir Instagram",
    gcList: "Entrar na GC List"
  },
  ht: {
    title: "Kat vityèl demo",
    text:
      "Kat reyèl ou a ap jenere pa ekip Golden Circle apre yo kreye kont manm ou.",
    account: "Espas mwen",
    instagram: "Swiv Instagram",
    gcList: "Antre nan GC List"
  }
} satisfies Record<Locale, Record<string, string>>;

export default async function CardPage({
  params
}: {
  params: Promise<{ locale: string }>;
}) {
  const resolvedParams = await params;

  if (!isLocale(resolvedParams.locale)) {
    notFound();
  }

  const copy = memberPageText[resolvedParams.locale];
  const pageCopy = cardPageCopy[resolvedParams.locale];

  return (
    <main className="section-shell py-14 md:py-20">
      <SectionHeader title={copy.cardTitle} text={copy.cardText} />
      <section className="premium-border mt-10 rounded-lg bg-coal/86 p-6 shadow-card">
        <p className="text-xs font-black uppercase tracking-[0.24em] text-gold">
          {pageCopy.title}
        </p>
        <p className="mt-3 max-w-3xl text-sm leading-7 text-mist">
          {pageCopy.text}
        </p>
        <div className="mt-6 grid gap-3 sm:grid-cols-3">
          <CTAButton href={`/${resolvedParams.locale}/account`} icon={ShieldCheck}>
            {pageCopy.account}
          </CTAButton>
          <CTAButton href={links.gcList} external variant="secondary" icon={Users}>
            {pageCopy.gcList}
          </CTAButton>
          <CTAButton href={links.instagram} external variant="ghost" icon={Instagram}>
            {pageCopy.instagram}
          </CTAButton>
        </div>
      </section>
      <div className="mt-10">
        <MemberCard member={demoMembers[0]} locale={resolvedParams.locale} />
      </div>
    </main>
  );
}
