import { CreditCard, Instagram, ShieldCheck, Sparkles, Users } from "lucide-react";
import { notFound } from "next/navigation";
import { CTAButton } from "@/components/CTAButton";
import { SectionHeader } from "@/components/SectionHeader";
import { getDictionary, isLocale, links, type Locale } from "@/lib/i18n";
import { demoMembers } from "@/lib/members";

const accountCopy = {
  fr: {
    title: "Mon espace Golden Circle",
    text: "Retrouvez votre statut, votre carte virtuelle et vos accès Golden Circle.",
    notice:
      "L’accès compte complet sera activé progressivement. En attendant, votre carte virtuelle peut être générée par l’équipe Golden Circle.",
    card: "Voir ma carte virtuelle",
    status: "Vérifier mon statut",
    list: "Rejoindre la GC List",
    vip: "Passer VIP",
    instagram: "Contacter / Suivre Instagram",
    spaces: "Explorer les espaces"
  },
  en: {
    title: "My Golden Circle space",
    text: "Find your status, your virtual card and your Golden Circle access.",
    notice:
      "Full account access will be activated progressively. For now, your virtual card can be generated by the Golden Circle team.",
    card: "View my virtual card",
    status: "Check my status",
    list: "Join the GC List",
    vip: "Go VIP",
    instagram: "Contact / Follow Instagram",
    spaces: "Explore spaces"
  },
  es: {
    title: "Mi espacio Golden Circle",
    text: "Encuentra tu estado, tu tarjeta virtual y tus accesos Golden Circle.",
    notice:
      "El acceso completo a la cuenta se activará progresivamente. Mientras tanto, el equipo Golden Circle puede generar tu tarjeta virtual.",
    card: "Ver mi tarjeta virtual",
    status: "Verificar mi estado",
    list: "Unirse a la GC List",
    vip: "Pasar a VIP",
    instagram: "Contactar / Seguir Instagram",
    spaces: "Explorar espacios"
  },
  pt: {
    title: "Meu espaço Golden Circle",
    text: "Encontre seu status, seu cartão virtual e seus acessos Golden Circle.",
    notice:
      "O acesso completo à conta será ativado progressivamente. Por enquanto, seu cartão virtual pode ser gerado pela equipe Golden Circle.",
    card: "Ver meu cartão virtual",
    status: "Verificar meu status",
    list: "Entrar na GC List",
    vip: "Passar para VIP",
    instagram: "Contato / Seguir Instagram",
    spaces: "Explorar espaços"
  },
  ht: {
    title: "Espas Golden Circle mwen",
    text: "Jwenn estati ou, kat vityèl ou ak aksè Golden Circle ou yo.",
    notice:
      "Aksè kont konplè a ap aktive piti piti. Pou kounye a, ekip Golden Circle ka jenere kat vityèl ou.",
    card: "Gade kat vityèl mwen",
    status: "Verifye estati mwen",
    list: "Antre nan GC List",
    vip: "Pase VIP",
    instagram: "Kontakte / Swiv Instagram",
    spaces: "Eksplore espas yo"
  }
} satisfies Record<Locale, Record<string, string>>;

export default async function AccountPage({
  params
}: {
  params: Promise<{ locale: string }>;
}) {
  const resolvedParams = await params;

  if (!isLocale(resolvedParams.locale)) {
    notFound();
  }

  const locale = resolvedParams.locale;
  const dictionary = getDictionary(locale);
  const copy = accountCopy[locale];
  const demoSecretId = demoMembers[0].secretId;

  return (
    <main className="section-shell py-14 md:py-20">
      <SectionHeader title={copy.title} text={copy.text} />

      <section className="premium-border mt-10 rounded-lg bg-gradient-to-br from-coal via-ruby/20 to-black p-6 shadow-card">
        <p className="max-w-3xl text-sm leading-7 text-mist">{copy.notice}</p>
        <div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          <CTAButton href={`/${locale}/card/${demoSecretId}`} icon={CreditCard}>
            {copy.card}
          </CTAButton>
          <CTAButton href={`/${locale}/card`} variant="secondary" icon={ShieldCheck}>
            {copy.status}
          </CTAButton>
          <CTAButton href={links.gcList} external variant="secondary" icon={Users}>
            {copy.list}
          </CTAButton>
          <CTAButton href={links.vipList} external variant="secondary" icon={Sparkles}>
            {copy.vip}
          </CTAButton>
          <CTAButton href={links.instagram} external variant="ghost" icon={Instagram}>
            {copy.instagram}
          </CTAButton>
          <CTAButton href={`/${locale}/spaces`} variant="ghost" icon={ShieldCheck}>
            {copy.spaces}
          </CTAButton>
        </div>
      </section>

      <section className="mt-8 grid gap-4 md:grid-cols-2">
        <article className="rounded-lg border border-white/10 bg-coal/82 p-5">
          <p className="text-xs font-black uppercase tracking-[0.24em] text-gold">
            {dictionary.nav.account}
          </p>
          <h2 className="mt-3 font-display text-3xl font-bold text-white">
            GOLDEN CIRCLE Caraïbes
          </h2>
          <p className="mt-3 text-sm leading-7 text-mist">
            {dictionary.footer.line}
          </p>
        </article>
        <article className="rounded-lg border border-white/10 bg-coal/82 p-5">
          <p className="text-xs font-black uppercase tracking-[0.24em] text-gold">
            Carte demo
          </p>
          <p className="mt-3 font-mono text-lg font-bold text-champagne">
            {demoSecretId}
          </p>
          <p className="mt-3 text-sm leading-7 text-mist">
            /{locale}/card/{demoSecretId}
          </p>
        </article>
      </section>
    </main>
  );
}
